//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruitmentPortal.WebApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RecruitmentPortal.WebApp.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed Extensions for file is .jpeg, .jpg, .png.
        /// </summary>
        public static string AllowImageExtensions {
            get {
                return ResourceManager.GetString("AllowImageExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidate Name is Required.
        /// </summary>
        public static string CandidateNameRequired {
            get {
                return ResourceManager.GetString("CandidateNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current CTC is Required.
        /// </summary>
        public static string CurrentCTCRequired {
            get {
                return ResourceManager.GetString("CurrentCTCRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth is Required.
        /// </summary>
        public static string DateofBirthRequired {
            get {
                return ResourceManager.GetString("DateofBirthRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date &amp; Time is Required.
        /// </summary>
        public static string DateTimeRequired {
            get {
                return ResourceManager.GetString("DateTimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t Deactivate as Data is being used by Application..
        /// </summary>
        public static string DeactivationFailed {
            get {
                return ResourceManager.GetString("DeactivationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree is Required.
        /// </summary>
        public static string DegreeNameRequired {
            get {
                return ResourceManager.GetString("DegreeNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest Qualification is Required.
        /// </summary>
        public static string DegreeRequired {
            get {
                return ResourceManager.GetString("DegreeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department is Required.
        /// </summary>
        public static string DeptNameRequired {
            get {
                return ResourceManager.GetString("DeptNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eligibility Criteria is Required.
        /// </summary>
        public static string EligibilityCriteriaRequired {
            get {
                return ResourceManager.GetString("EligibilityCriteriaRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is Required.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Item for Editing.
        /// </summary>
        public static string EnableEntity {
            get {
                return ResourceManager.GetString("EnableEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date must be greater than or equal to start date.
        /// </summary>
        public static string EndDateGreaterThanStartDate {
            get {
                return ResourceManager.GetString("EndDateGreaterThanStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected CTC is Required.
        /// </summary>
        public static string ExpectedCTCRequired {
            get {
                return ResourceManager.GetString("ExpectedCTCRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience is Required.
        /// </summary>
        public static string ExperienceRequired {
            get {
                return ResourceManager.GetString("ExperienceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is Required.
        /// </summary>
        public static string FileRequired {
            get {
                return ResourceManager.GetString("FileRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender is Required.
        /// </summary>
        public static string GenderRequired {
            get {
                return ResourceManager.GetString("GenderRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HSC Percentage is Required.
        /// </summary>
        public static string HSCPercentageRequired {
            get {
                return ResourceManager.GetString("HSCPercentageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose the Interviewer.
        /// </summary>
        public static string InterviewerRequired {
            get {
                return ResourceManager.GetString("InterviewerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select the mode of Interview.
        /// </summary>
        public static string InterviewModeRequired {
            get {
                return ResourceManager.GetString("InterviewModeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Provide valid Email Address.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP is Invalid.
        /// </summary>
        public static string InvalidOTP {
            get {
                return ResourceManager.GetString("InvalidOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Category is Required.
        /// </summary>
        public static string JobCategoryRequired {
            get {
                return ResourceManager.GetString("JobCategoryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Role is Required.
        /// </summary>
        public static string JobRoleRequired {
            get {
                return ResourceManager.GetString("JobRoleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title is Required.
        /// </summary>
        public static string JobTitleRequired {
            get {
                return ResourceManager.GetString("JobTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Type is Required.
        /// </summary>
        public static string JobTypeRequired {
            get {
                return ResourceManager.GetString("JobTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location is Required.
        /// </summary>
        public static string LocationRequired {
            get {
                return ResourceManager.GetString("LocationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum allowed file size is 3 MB.
        /// </summary>
        public static string MaxSize3MB {
            get {
                return ResourceManager.GetString("MaxSize3MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode of Interview is Required.
        /// </summary>
        public static string ModeofInterviewRequired {
            get {
                return ResourceManager.GetString("ModeofInterviewRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice Period is Required.
        /// </summary>
        public static string NoticePeriodRequired {
            get {
                return ResourceManager.GetString("NoticePeriodRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is Required.
        /// </summary>
        public static string Passwordrequired {
            get {
                return ResourceManager.GetString("Passwordrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone No is Required.
        /// </summary>
        public static string PhoneRequired {
            get {
                return ResourceManager.GetString("PhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- Please Select ---.
        /// </summary>
        public static string PleaseSelect {
            get {
                return ResourceManager.GetString("PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Position is Required.
        /// </summary>
        public static string PositionRequired {
            get {
                return ResourceManager.GetString("PositionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating is Required.
        /// </summary>
        public static string RatingRequired {
            get {
                return ResourceManager.GetString("RatingRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference is Required.
        /// </summary>
        public static string ReferenceRequired {
            get {
                return ResourceManager.GetString("ReferenceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejection Reason is Required.
        /// </summary>
        public static string RejectionReasonRequired {
            get {
                return ResourceManager.GetString("RejectionReasonRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relevent Experience is Required.
        /// </summary>
        public static string ReleventExperienceRequired {
            get {
                return ResourceManager.GetString("ReleventExperienceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark is Required.
        /// </summary>
        public static string RemarkRequired {
            get {
                return ResourceManager.GetString("RemarkRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume is Required.
        /// </summary>
        public static string ResumeRequired {
            get {
                return ResourceManager.GetString("ResumeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round is Required.
        /// </summary>
        public static string RoundRequired {
            get {
                return ResourceManager.GetString("RoundRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Round is Required.
        /// </summary>
        public static string RoundTypeRequired {
            get {
                return ResourceManager.GetString("RoundTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills is Required.
        /// </summary>
        public static string SkillsRequired {
            get {
                return ResourceManager.GetString("SkillsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype Id is Required.
        /// </summary>
        public static string SkypeIdRequired {
            get {
                return ResourceManager.GetString("SkypeIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something Went wrong. Please try again later..
        /// </summary>
        public static string SomethingWrong {
            get {
                return ResourceManager.GetString("SomethingWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSC Percentage is Required.
        /// </summary>
        public static string SSCPercentageRequired {
            get {
                return ResourceManager.GetString("SSCPercentageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status is Required.
        /// </summary>
        public static string StatusRequired {
            get {
                return ResourceManager.GetString("StatusRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select InterviewStatus.
        /// </summary>
        public static string StatusValueRequired {
            get {
                return ResourceManager.GetString("StatusValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Submitted Successfully.
        /// </summary>
        public static string SuccessfullyApplied {
            get {
                return ResourceManager.GetString("SuccessfullyApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Experience is Required.
        /// </summary>
        public static string TotalExperienceRequired {
            get {
                return ResourceManager.GetString("TotalExperienceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name is Required.
        /// </summary>
        public static string UserNameRequired {
            get {
                return ResourceManager.GetString("UserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacancy is Required.
        /// </summary>
        public static string VacancyRequired {
            get {
                return ResourceManager.GetString("VacancyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid Candidate Name is SRequired.
        /// </summary>
        public static string ValidCandidateNameRequired {
            get {
                return ResourceManager.GetString("ValidCandidateNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid CTC is Required.
        /// </summary>
        public static string ValidCTCRequired {
            get {
                return ResourceManager.GetString("ValidCTCRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HSC % must be greater than 0.
        /// </summary>
        public static string ValidHSCRequired {
            get {
                return ResourceManager.GetString("ValidHSCRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone No must be equal to 10 digits.
        /// </summary>
        public static string ValidPhoneRequired {
            get {
                return ResourceManager.GetString("ValidPhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSC % must be greater than 0.
        /// </summary>
        public static string ValidSSCRequired {
            get {
                return ResourceManager.GetString("ValidSSCRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid Input Text Required.
        /// </summary>
        public static string ValidTextRequired {
            get {
                return ResourceManager.GetString("ValidTextRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid Vacancy is Required.
        /// </summary>
        public static string ValidVacancyRequired {
            get {
                return ResourceManager.GetString("ValidVacancyRequired", resourceCulture);
            }
        }
    }
}
